### ISSUE TITLE
Image list generator

### ISSUE THREAD

**Issue by Elsword016** [abcucberkeley/LLSM_Processing_GUI#49]
Hello! 
I want to clear some doubts regarding Image List generator. I have 47 xyz tiles in .tif format  that i want to stitch in a 6x8 grid.

1. Custom patterns: My filenames are named as "8_100x_2024-06-12_14.01.03_deconvolved_F00.tif", ..... So in the Custom patterns box, should I input the entire filename or just F00,F01..F46?

2. I am bit confused about the Tile patterns. My images are single channels and have no time axis

Thanking you.

**Comment by MattHazard** [comment]
Hello,

1. Since you only have one channel you will only have one pattern. It can be anything that is present in the file names of all the files you want to include in that single channel. I.E. something like 8_100x_2024 for you. Usually we separate our channels with something like CamA_ch0 and use that as the custom pattern for that channel.

2. To use the image list generator, you need to have file names that follow some sort of convention in order for the grid to be formed. You can have a look at our [demo data](https://www.dropbox.com/scl/fi/sp1pz423jw6gpozab5yrf/PetaKit5D_2P_Confocal_Phase_Widefield_demo_datasets.tar?rlkey=i4wrwvphm9hz78z3kcqomqm1b&st=az3w6z0v&dl=1) and its corresponding [example](https://github.com/abcucberkeley/PetaKit5D-GUI/wiki/2.-Step%E2%80%90By%E2%80%90Step-Examples#4-image-list-generator-phase-dataset) for how we name our files. If you only want to stitch in xy then I believe you can leave the z, ch, and time patterns blank or have them all the same in all the files. So if you set X to 000x and Y to 000y with the others blank then your file names could look something like 8_100x_2024-06-12_14.01.03_deconvolved_000x_000y.tif, 8_100x_2024-06-12_14.01.03_deconvolved_001x_000y.tif, 8_100x_2024-06-12_14.01.03_deconvolved_000x_001y.tif, 8_100x_2024-06-12_14.01.03_deconvolved_001x_001y.tif, etc.

I hope this helps to clarify things for you.

Best,

Matthew Mueller

**Comment by Elsword016** [comment]
Thank you so much. I will try with the suggestions!
